### Cloud ###

- name: Deploy the cloud app
  hosts: ssi_cloud
  become: true
  collections:
    - community.docker

  tasks:
    - name: Start the authorities app
      docker_container:
        name: "{{ authorities_app_name }}"
        image: "{{ base_app_image }}"
        pull: true
        state: started
        env:
          AGENT_HOST: "{{ inventory_hostname }}"
          AGENT_PORT: "{{ authorities_agent_port }}"
          AGENT_ADMIN_PORT: "{{ authorities_admin_port }}"
          AGENT_LABEL: "{{ authorities_label }}"
          AGENT_SEED: "{{ authorities_seed }}"
          AGENT_INDY_NYM: "{{ authorities_nym }}"
          WEB_PORT: "{{ authorities_web_port }}"
        ports:
          - "{{ authorities_agent_port }}:{{ authorities_agent_port }}"
          - "{{ authorities_admin_port }}:{{ authorities_admin_port }}"
          - "{{ authorities_web_port }}:{{ authorities_web_port }}"
        command: uvicorn app.app_authorities.main:app --host 0.0.0.0 --port 3002
        etc_hosts:
          "ssi-cloud": "{{ ssi_cloud_ip }}"
          "ssi-edge-alpha": "{{ ssi_edge_alpha_ip }}"
          "ssi-edge-beta": "{{ ssi_edge_beta_ip }}"
          "ssi-ground": "{{ ssi_ground_ip }}"

### Edge Admins ###

- name: Deploy the edge alpha admin app
  hosts: ssi_edge_alpha
  become: true
  collections:
    - community.docker

  tasks:
    - name: Start the edge admin app
      docker_container:
        name: "{{ edge_alpha_app_name }}"
        image: "{{ base_app_image }}"
        pull: true
        state: started
        env:
          AGENT_HOST: "{{ inventory_hostname }}"
          AGENT_PORT: "{{ edge_alpha_agent_port }}"
          AGENT_ADMIN_PORT: "{{ edge_alpha_admin_port }}"
          AGENT_LABEL: "{{ edge_alpha_label }}"
          AGENT_SEED: "{{ edge_alpha_seed }}"
          AGENT_INDY_NYM: "{{ edge_alpha_nym }}"
          AUTHORITY_WEB_URL: "http://ssi-cloud:3002"
          EDGE_ALPHA_WEB_URL: "http://ssi-edge-alpha:4002"
          EDGE_BETA_WEB_URL: "http://ssi-edge-beta:4005"
          APP_SHUTDOWN_DELAY: "{{ app_shutdown_delay }}"
        ports:
          - "{{ edge_alpha_agent_port }}:{{ edge_alpha_agent_port }}"
          - "{{ edge_alpha_admin_port }}:{{ edge_alpha_admin_port }}"
          - "{{ edge_alpha_web_port }}:{{ edge_alpha_web_port }}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        command: uvicorn app.app_edge.main:app --host 0.0.0.0 --port 4002
        etc_hosts:
          "ssi-cloud": "{{ ssi_cloud_ip }}"
          "ssi-edge-alpha": "{{ ssi_edge_alpha_ip }}"
          "ssi-edge-beta": "{{ ssi_edge_beta_ip }}"
          "ssi-ground": "{{ ssi_ground_ip }}"

- name: Deploy the edge beta admin app
  hosts: ssi_edge_beta
  become: true
  collections:
    - community.docker

  tasks:
    - name: Start the edge admin app
      docker_container:
        name: "{{ edge_beta_app_name }}"
        image: "{{ base_app_image }}"
        pull: true
        state: started
        env:
          AGENT_HOST: "{{ inventory_hostname }}"
          AGENT_PORT: "{{ edge_beta_agent_port }}"
          AGENT_ADMIN_PORT: "{{ edge_beta_admin_port }}"
          AGENT_LABEL: "{{ edge_beta_label }}"
          AGENT_SEED: "{{ edge_beta_seed }}"
          AGENT_INDY_NYM: "{{ edge_beta_nym }}"
          AUTHORITY_WEB_URL: "http://ssi-cloud:3002"
          EDGE_ALPHA_WEB_URL: "http://ssi-edge-alpha:4002"
          EDGE_BETA_WEB_URL: "http://ssi-edge-beta:4005"
          APP_SHUTDOWN_DELAY: "{{ app_shutdown_delay }}"
        ports:
          - "{{ edge_beta_agent_port }}:{{ edge_beta_agent_port }}"
          - "{{ edge_beta_admin_port }}:{{ edge_beta_admin_port }}"
          - "{{ edge_beta_web_port }}:{{ edge_beta_web_port }}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        command: uvicorn app.app_edge.main:app --host 0.0.0.0 --port 4005
        etc_hosts:
          "ssi-cloud": "{{ ssi_cloud_ip }}"
          "ssi-edge-alpha": "{{ ssi_edge_alpha_ip }}"
          "ssi-edge-beta": "{{ ssi_edge_beta_ip }}"
          "ssi-ground": "{{ ssi_ground_ip }}"

### Digital Twins ###

- name: Deploy the car twin app
  hosts: ssi_edge_alpha
  become: true
  collections:
    - community.docker

  tasks:
    - name: Start the car twin app
      docker_container:
        name: "{{ car_twin_app_name }}"
        image: "{{ base_app_image }}"
        pull: true
        state: started
        env:
          AGENT_HOST: "{{ inventory_hostname }}"
          AGENT_PORT: "{{ car_twin_agent_port }}"
          AGENT_ADMIN_PORT: "{{ car_twin_admin_port }}"
          AGENT_LABEL: "{{ car_twin_label }}"
          AGENT_SEED: "{{ car_twin_seed }}"
          AGENT_INDY_NYM: "{{ car_twin_nym }}"
          EDGE_NAME: "{{ edge_alpha_label }}"
          AUTHORITY_WEB_URL: "http://ssi-cloud:3002"
          EDGE_ALPHA_WEB_URL: "http://ssi-edge-alpha:4002"
          EDGE_BETA_WEB_URL: "http://ssi-edge-beta:4005"
          CAR_WEB_URL: "http://ssi-ground:6002"
          TWIN_DRONE_WEB_URL: "http://ssi-edge-alpha:5005"
        ports:
          - "{{ car_twin_agent_port }}:{{ car_twin_agent_port }}"
          - "{{ car_twin_admin_port }}:{{ car_twin_admin_port }}"
          - "{{ car_twin_web_port }}:{{ car_twin_web_port }}"
        command: uvicorn app.app_digital_twin_car.main:app --host 0.0.0.0 --port 5002
        etc_hosts:
          "ssi-cloud": "{{ ssi_cloud_ip }}"
          "ssi-edge-alpha": "{{ ssi_edge_alpha_ip }}"
          "ssi-edge-beta": "{{ ssi_edge_beta_ip }}"
          "ssi-ground": "{{ ssi_ground_ip }}"

- name: Deploy the drone twin app
  hosts: ssi_edge_alpha
  become: true
  collections:
    - community.docker

  tasks:
    - name: Start the drone twin app
      docker_container:
        name: "{{ drone_twin_app_name }}"
        image: "{{ base_app_image }}"
        pull: true
        state: started
        env:
          AGENT_HOST: "{{ inventory_hostname }}"
          AGENT_PORT: "{{ drone_twin_agent_port }}"
          AGENT_ADMIN_PORT: "{{ drone_twin_admin_port }}"
          AGENT_LABEL: "{{ drone_twin_label }}"
          AGENT_SEED: "{{ drone_twin_seed }}"
          AGENT_INDY_NYM: "{{ drone_twin_nym }}"
          EDGE_NAME: "{{ edge_alpha_label }}"
          AUTHORITY_WEB_URL: "http://ssi-cloud:3002"
          EDGE_ALPHA_WEB_URL: "http://ssi-edge-alpha:4002"
          EDGE_BETA_WEB_URL: "http://ssi-edge-beta:4005"
          CAR_WEB_URL: "http://ssi-ground:6002"
        ports:
          - "{{ drone_twin_agent_port }}:{{ drone_twin_agent_port }}"
          - "{{ drone_twin_admin_port }}:{{ drone_twin_admin_port }}"
          - "{{ drone_twin_web_port }}:{{ drone_twin_web_port }}"
        command: uvicorn app.app_digital_twin_drone.main:app --host 0.0.0.0 --port 5005
        etc_hosts:
          "ssi-cloud": "{{ ssi_cloud_ip }}"
          "ssi-edge-alpha": "{{ ssi_edge_alpha_ip }}"
          "ssi-edge-beta": "{{ ssi_edge_beta_ip }}"
          "ssi-ground": "{{ ssi_ground_ip }}"

### Car ###

- name: Deploy the car app
  hosts: ssi_ground
  become: true
  collections:
    - community.docker

  tasks:
    - name: Start the car app
      docker_container:
        name: "{{ car_app_name }}"
        image: "{{ base_app_image }}"
        pull: true
        state: started
        env:
          AGENT_HOST: "{{ inventory_hostname }}"
          AGENT_PORT: "{{ car_agent_port }}"
          AGENT_ADMIN_PORT: "{{ car_admin_port }}"
          AGENT_LABEL: "{{ car_label }}"
          AGENT_SEED: "{{ car_seed }}"
          AGENT_INDY_NYM: "{{ car_nym }}"
          AUTHORITY_WEB_URL: "http://ssi-cloud:3002"
          WEB_PORT: "{{ car_web_port }}"
        ports:
          - "{{ car_agent_port }}:{{ car_agent_port }}"
          - "{{ car_admin_port }}:{{ car_admin_port }}"
          - "{{ car_web_port }}:{{ car_web_port }}"
        command: uvicorn app.app_car.main:app --host 0.0.0.0 --port 6002
        etc_hosts:
          "ssi-cloud": "{{ ssi_cloud_ip }}"
          "ssi-edge-alpha": "{{ ssi_edge_alpha_ip }}"
          "ssi-edge-beta": "{{ ssi_edge_beta_ip }}"
          "ssi-ground": "{{ ssi_ground_ip }}"

### Drone ###

- name: Deploy the drone app
  hosts: ssi_ground
  become: true
  collections:
    - community.docker

  tasks:
    - name: Start the drone app
      docker_container:
        name: "{{ drone_app_name }}"
        image: "{{ base_app_image }}"
        pull: true
        state: started
        env:
          AGENT_HOST: "{{ inventory_hostname }}"
          AGENT_PORT: "{{ drone_agent_port }}"
          AGENT_ADMIN_PORT: "{{ drone_admin_port }}"
          AGENT_LABEL: "{{ drone_label }}"
          AGENT_SEED: "{{ drone_seed }}"
          AGENT_INDY_NYM: "{{ drone_nym }}"
          AUTHORITY_WEB_URL: "http://ssi-cloud:3002"
          WEB_PORT: "{{ drone_web_port }}"
        ports:
          - "{{ drone_agent_port }}:{{ drone_agent_port }}"
          - "{{ drone_admin_port }}:{{ drone_admin_port }}"
          - "{{ drone_web_port }}:{{ drone_web_port }}"
        command: uvicorn app.app_drone.main:app --host 0.0.0.0 --port 6005
        etc_hosts:
          "ssi-cloud": "{{ ssi_cloud_ip }}"
          "ssi-edge-alpha": "{{ ssi_edge_alpha_ip }}"
          "ssi-edge-beta": "{{ ssi_edge_beta_ip }}"
          "ssi-ground": "{{ ssi_ground_ip }}"