- name: Deploy the cloud apps (authorities and cloud agent)
  hosts: ssi_cloud
  become: true
  collections:
    - community.docker
  
  tasks:
    - name: Start the authorities app
      docker_container:
        name: ma-ssi-authorities
        image: "{{ app_authorities_image }}"
        pull: true
        state: started
        env:
          AGENT_HOST: "ssi-cloud"
          AGENT_PORT: "3000"
          WEB_PORT: "3001"
          INIT_CRED_DEF_RECORD: "true"
        ports:
          - "3000:3000"
          - "3001:3001"
        etc_hosts:
          "ssi-cloud": "{{ ssi_cloud_ip }}"
          "ssi-edge-alpha": "{{ ssi_edge_alpha_ip }}"
          "ssi-edge-beta": "{{ ssi_edge_beta_ip }}"

    - name: Start the cloud agent app
      docker_container:
        name: ma-ssi-cloud-agent
        image: "{{ app_cloud_agent_image }}"
        pull: true
        state: started
        env:
          AGENT_HOST: "ssi-cloud"
          AGENT_PORT: "3002"
          WEB_PORT: "3003"
        ports:
          - "3002:3002"
          - "3003:3003"
        etc_hosts:
          "ssi-cloud": "{{ ssi_cloud_ip }}"
          "ssi-edge-alpha": "{{ ssi_edge_alpha_ip }}"
          "ssi-edge-beta": "{{ ssi_edge_beta_ip }}"      
  